import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { env } from '../config/env.js';
import { AppError } from '../middleware/errorHandler.js';

type Extension = 'jpeg' | 'png' | 'webp';
async function localUpload(bytes: Buffer, extension: Extension) { const directory = path.resolve(process.cwd(), env.UPLOAD_DIR, 'products'); await fs.mkdir(directory, { recursive: true }); const fileName = `${Date.now()}-${crypto.randomBytes(10).toString('hex')}.${extension === 'jpeg' ? 'jpg' : extension}`; await fs.writeFile(path.join(directory, fileName), bytes, { flag: 'wx' }); const relative = `/uploads/products/${fileName}`; return env.UPLOAD_PUBLIC_BASE_URL ? `${env.UPLOAD_PUBLIC_BASE_URL.replace(/\/$/, '')}${relative}` : relative; }
async function cloudinaryUpload(bytes: Buffer, mimeType: string) { if (!env.CLOUDINARY_CLOUD_NAME || !env.CLOUDINARY_API_KEY || !env.CLOUDINARY_API_SECRET) throw new AppError(503, 'Cloud image storage is not configured'); const timestamp = Math.floor(Date.now() / 1000); const folder = 'sweety-birds-fishes/products'; const signature = crypto.createHash('sha1').update(`folder=${folder}&timestamp=${timestamp}${env.CLOUDINARY_API_SECRET}`).digest('hex'); const form = new FormData(); form.append('file', new Blob([Uint8Array.from(bytes)], { type: mimeType }), 'product-image'); form.append('api_key', env.CLOUDINARY_API_KEY); form.append('timestamp', String(timestamp)); form.append('folder', folder); form.append('signature', signature); const response = await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(env.CLOUDINARY_CLOUD_NAME)}/image/upload`, { method: 'POST', body: form, signal: AbortSignal.timeout(30_000) }); const body = await response.json().catch(() => ({})) as { secure_url?: string; error?: { message?: string } }; if (!response.ok || !body.secure_url) throw new AppError(502, body.error?.message || 'Cloud image upload failed'); return body.secure_url; }
export async function storeProductImage(bytes: Buffer, extension: Extension, mimeType: string) { return env.IMAGE_STORAGE_PROVIDER === 'cloudinary' ? cloudinaryUpload(bytes, mimeType) : localUpload(bytes, extension); }
