import type { NextFunction, Request, Response } from 'express';
import { z } from 'zod';
import { prisma } from '../config/prisma.js';
import { AppError } from '../middleware/errorHandler.js';
import { ok } from '../utils/apiResponse.js';

const rangeSchema = z.object({ from: z.coerce.date().optional(), to: z.coerce.date().optional() });
function range(query: Request['query']) { const parsed = rangeSchema.parse(query); const to = parsed.to || new Date(); const from = parsed.from || new Date(to.getTime() - 29 * 86400000); if (from > to) throw new AppError(422, 'From date must be before to date'); if (to.getTime() - from.getTime() > 731 * 86400000) throw new AppError(422, 'Analytics range cannot exceed two years'); to.setHours(23, 59, 59, 999); from.setHours(0, 0, 0, 0); return { from, to }; }
function addressDistrict(snapshot: unknown) { if (!snapshot || typeof snapshot !== 'object') return 'Unknown'; const value = (snapshot as Record<string, unknown>).district; return typeof value === 'string' && value.trim() ? value.trim() : 'Unknown'; }

export async function analyticsOverview(req: Request, res: Response, next: NextFunction) {
  try {
    res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate');
    const { from, to } = range(req.query); const createdAt = { gte: from, lte: to }; const paidWhere = { paymentStatus: 'PAID' as const, createdAt };
    const [orders, productCount, lowStock, alertGroups] = await Promise.all([
      prisma.order.findMany({ where: paidWhere, select: { id: true, userId: true, total: true, status: true, createdAt: true, receivedAt: true, deliveryAddressSnapshot: true, items: { select: { productId: true, productName: true, category: true, quantity: true, lineTotal: true } } } }),
      prisma.product.count({ where: { status: { not: 'ARCHIVED' } } }),
      prisma.product.findMany({ where: { status: { not: 'ARCHIVED' }, stock: { lte: 5 } }, select: { id: true, name: true, stock: true, status: true, category: true }, orderBy: [{ stock: 'asc' }, { name: 'asc' }], take: 50 }),
      prisma.availabilityAlert.groupBy({ by: ['productId'], where: { isActive: true }, _count: { _all: true }, orderBy: { _count: { productId: 'desc' } }, take: 20 }),
    ]);
    const revenue = orders.reduce((sum, order) => sum + Number(order.total), 0); const received = orders.filter(order => order.status === 'RECEIVED').length; const cancelled = await prisma.order.count({ where: { status: 'CANCELLED', createdAt } });
    const categories = new Map<string, { revenue: number; units: number }>(); const products = new Map<string, { productId: string; name: string; revenue: number; units: number }>(); const districts = new Map<string, { orders: number; revenue: number }>(); const days = new Map<string, { revenue: number; orders: number }>(); const customers = new Map<string, { orders: number; spent: number }>();
    for (const order of orders) { const total = Number(order.total); const day = order.createdAt.toISOString().slice(0, 10); const dayRow = days.get(day) || { revenue: 0, orders: 0 }; dayRow.revenue += total; dayRow.orders += 1; days.set(day, dayRow); const district = addressDistrict(order.deliveryAddressSnapshot); const districtRow = districts.get(district) || { orders: 0, revenue: 0 }; districtRow.orders += 1; districtRow.revenue += total; districts.set(district, districtRow); const customer = customers.get(order.userId) || { orders: 0, spent: 0 }; customer.orders += 1; customer.spent += total; customers.set(order.userId, customer); for (const item of order.items) { const line = Number(item.lineTotal); const category = categories.get(item.category) || { revenue: 0, units: 0 }; category.revenue += line; category.units += item.quantity; categories.set(item.category, category); const product = products.get(item.productId) || { productId: item.productId, name: item.productName, revenue: 0, units: 0 }; product.revenue += line; product.units += item.quantity; products.set(item.productId, product); } }
    const topCustomerIds = [...customers.entries()].sort((a, b) => b[1].spent - a[1].spent).slice(0, 10).map(([id]) => id); const userRows = await prisma.user.findMany({ where: { id: { in: topCustomerIds } }, select: { id: true, name: true, email: true } }); const userMap = new Map(userRows.map(user => [user.id, user])); const alertProductIds = alertGroups.map(row => row.productId); const alertProducts = await prisma.product.findMany({ where: { id: { in: alertProductIds } }, select: { id: true, name: true, stock: true, status: true } }); const alertMap = new Map(alertProducts.map(product => [product.id, product]));
    return ok(res, { range: { from, to }, metrics: { revenue, paidOrders: orders.length, averageOrderValue: orders.length ? revenue / orders.length : 0, receivedOrders: received, cancelledOrders: cancelled, fulfillmentRate: orders.length ? received / orders.length * 100 : 0, uniqueCustomers: customers.size, activeProducts: productCount }, revenueTrend: [...days.entries()].sort().map(([date, value]) => ({ date, ...value })), categories: [...categories.entries()].map(([category, value]) => ({ category, ...value })).sort((a, b) => b.revenue - a.revenue), topProducts: [...products.values()].sort((a, b) => b.revenue - a.revenue).slice(0, 10), districts: [...districts.entries()].map(([district, value]) => ({ district, ...value })).sort((a, b) => b.orders - a.orders).slice(0, 10), topCustomers: [...customers.entries()].sort((a, b) => b[1].spent - a[1].spent).slice(0, 10).map(([id, value]) => ({ userId: id, name: userMap.get(id)?.name || 'Customer', email: userMap.get(id)?.email || '', ...value })), lowStock, availabilityDemand: alertGroups.map(row => ({ productId: row.productId, name: alertMap.get(row.productId)?.name || 'Unavailable product', stock: alertMap.get(row.productId)?.stock ?? 0, status: alertMap.get(row.productId)?.status || 'ARCHIVED', alerts: row._count._all })) });
  } catch (error) { next(error); }
}

function csvCell(value: unknown) { const text = String(value ?? ''); return `"${text.replaceAll('"', '""')}"`; }
export async function analyticsCsv(req: Request, res: Response, next: NextFunction) {
  try { const { from, to } = range(req.query); const orders = await prisma.order.findMany({ where: { paymentStatus: 'PAID', createdAt: { gte: from, lte: to } }, include: { user: { select: { name: true, email: true } }, items: true }, orderBy: { createdAt: 'desc' } }); const rows = [['Order Number','Date','Customer','Email','Status','Products','Subtotal','Courier + Packing','Discount','Total'], ...orders.map(order => [order.orderNumber, order.createdAt.toISOString(), order.user.name, order.user.email, order.status, order.items.map(item => `${item.productName} x${item.quantity}`).join('; '), order.subtotal, order.shippingCharge, order.discount, order.total])]; const csv = rows.map(row => row.map(csvCell).join(',')).join('\r\n'); res.setHeader('Content-Type', 'text/csv; charset=utf-8'); res.setHeader('Content-Disposition', `attachment; filename="sales-${from.toISOString().slice(0,10)}-${to.toISOString().slice(0,10)}.csv"`); return res.status(200).send(`\uFEFF${csv}`); } catch (error) { next(error); }
}
