import { buildWhatsAppUrl } from '../../config/siteConfig';
import React, { useEffect, useState } from 'react';
import { ArrowUpRight, Fish, Mail, MapPin, MessageCircle, ShieldCheck, Sparkles, Truck } from 'lucide-react';
import { siteSettingsService, SiteSettings } from '../../services/siteSettingsService';

interface FooterProps { onNavigate: (route: string) => void; }
const FooterLink: React.FC<{ children: React.ReactNode; onClick: () => void }> = ({ children, onClick }) => <li><button onClick={onClick} className="group flex items-center gap-1.5 py-1 text-sky-100/75 hover:text-cyan-300 transition-colors"><span>{children}</span><ArrowUpRight className="w-3 h-3 opacity-0 -translate-x-1 group-hover:opacity-100 group-hover:translate-x-0 transition-all" /></button></li>;

export const Footer: React.FC<FooterProps> = ({ onNavigate }) => {
  const [settings, setSettings] = useState<SiteSettings>(() => siteSettingsService.getSettings());
  useEffect(() => siteSettingsService.subscribe(setSettings), []);
  return <footer id="app-footer" className="relative z-10 overflow-hidden bg-[#011b2b] text-[#E8F9FC] border-t border-cyan-400/15 pb-24 md:pb-8">
    <div aria-hidden="true" className="absolute inset-0 opacity-70 footer-water-glow" /><div aria-hidden="true" className="absolute -top-16 left-[8%] w-40 h-40 rounded-full border border-cyan-300/15 footer-bubble" /><div aria-hidden="true" className="absolute top-24 right-[10%] w-12 h-12 rounded-full border border-cyan-300/20 footer-bubble footer-bubble-delay" />
    <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-12">
      <div className="relative overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-gradient-to-r from-[#064b67] via-[#0875B5] to-[#0b5574] p-6 md:p-8 shadow-2xl shadow-black/20">
        <div className="absolute -right-12 -top-20 w-72 h-72 rounded-full bg-cyan-300/15 blur-3xl" /><div className="relative flex flex-col lg:flex-row lg:items-center justify-between gap-6"><div className="flex gap-4 items-center"><div className="w-14 h-14 rounded-2xl bg-white/12 border border-white/20 grid place-items-center"><Sparkles className="w-7 h-7 text-cyan-200" /></div><div><p className="text-cyan-200 text-xs font-extrabold uppercase tracking-[.18em]">Aquarium essentials</p><h2 className="text-2xl md:text-3xl font-extrabold mt-1">Bring more colour to your aquarium.</h2><p className="text-sky-100/80 text-sm mt-1">Explore guppies, fish food and seller-created combo packs.</p></div></div><button onClick={() => onNavigate('/shop')} className="premium-action-btn shrink-0 rounded-2xl bg-cyan-300 px-6 py-3.5 font-extrabold text-[#032B42] shadow-lg hover:bg-white transition-colors flex items-center justify-center gap-2">Explore the store <ArrowUpRight className="w-4 h-4" /></button></div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-9 lg:gap-12 py-12 border-b border-cyan-300/12">
        <div className="lg:col-span-2 space-y-5"><div className="flex items-center gap-3"><div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-[#0875B5] to-cyan-400 flex items-center justify-center text-white shadow-lg shadow-cyan-950/30"><Fish className="w-7 h-7 footer-fish" /></div><div><span className="font-extrabold text-xl text-white block leading-none">Sweety</span><span className="text-xs font-bold text-[#50D4EE] tracking-[.14em] uppercase">Birds &amp; Fishes</span></div></div><p className="text-sm text-sky-100/70 leading-relaxed max-w-md">A focused Tamil Nadu store for guppies, fish food and thoughtfully created combo packs.</p><div className="grid sm:grid-cols-2 gap-3 max-w-xl"><div className="rounded-2xl bg-white/5 border border-white/10 p-3 flex gap-3"><Truck className="w-5 h-5 text-cyan-300 shrink-0" /><p className="text-xs text-sky-100/75"><strong className="text-white block">Tamil Nadu delivery</strong>Enabled serviceable PIN codes only.</p></div><div className="rounded-2xl bg-white/5 border border-white/10 p-3 flex gap-3"><ShieldCheck className="w-5 h-5 text-emerald-300 shrink-0" /><p className="text-xs text-sky-100/75"><strong className="text-white block">Secure account access</strong>Email-verified customer accounts.</p></div></div></div>
        <div><h4 className="font-extrabold text-white uppercase tracking-[.14em] text-xs mb-4">Shop</h4><ul className="space-y-1 text-sm"><FooterLink onClick={() => onNavigate('/guppies')}>Guppies</FooterLink><FooterLink onClick={() => onNavigate('/fish-food')}>Fish Food</FooterLink><FooterLink onClick={() => onNavigate('/combo-packs')}>Combo Packs</FooterLink><FooterLink onClick={() => onNavigate('/shop')}>All Products</FooterLink></ul></div>
        <div><h4 className="font-extrabold text-white uppercase tracking-[.14em] text-xs mb-4">Learn &amp; Trust</h4><ul className="space-y-1 text-sm"><FooterLink onClick={() => onNavigate('/guppy-care')}>Guppy Care</FooterLink><FooterLink onClick={() => onNavigate('/guppy-care/summer-guppy-maintenance')}>Summer Care</FooterLink><FooterLink onClick={() => onNavigate('/guppy-care/guppy-breeding-tips')}>Breeding Tips</FooterLink><FooterLink onClick={() => onNavigate('/why-trust-us')}>Why Trust Us</FooterLink><FooterLink onClick={() => onNavigate('/about')}>About</FooterLink></ul></div>
        <div><h4 className="font-extrabold text-white uppercase tracking-[.14em] text-xs mb-4">Contact</h4><ul className="space-y-3 text-sm text-sky-100/75"><li className="flex items-start gap-2"><MessageCircle className="w-4 h-4 text-[#25D366] mt-0.5 shrink-0" /><a href={buildWhatsAppUrl('Hello Sweety Birds & Fishes, I have an enquiry.')} target="_blank" rel="noreferrer" className="hover:text-cyan-300">{settings.whatsappNumber}</a></li><li className="flex items-start gap-2"><Mail className="w-4 h-4 text-cyan-300 mt-0.5 shrink-0" /><a href={`mailto:${settings.email}`} className="hover:text-cyan-300 break-all">{settings.email}</a></li><li className="flex items-start gap-2"><MapPin className="w-4 h-4 text-cyan-300 mt-0.5 shrink-0" /><span>{settings.locationLabel}</span></li><FooterLink onClick={() => onNavigate('/contact')}>Contact &amp; FAQs</FooterLink></ul></div>
      </div>
      <div className="pt-6 flex flex-col sm:flex-row items-center justify-between text-xs text-sky-100/50 gap-3"><p>© 2026 Sweety Birds &amp; Fishes. All rights reserved.</p><span className="flex items-center gap-2"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" /> Guppies • Fish Food • Combo Packs</span></div>
    </div>
  </footer>;
};
