import React,{useCallback,useEffect,useState} from 'react';
import {AlertCircle,Loader2,LogIn,MessageSquare,RefreshCw,Send} from 'lucide-react';
import {toastService} from '../../services/toastService';
const API=(import.meta.env.VITE_API_BASE_URL||'http://localhost:4000/api').replace(/\/$/,'');
type Ticket={id:string;subject:string;message:string;sellerReply?:string|null;status:'OPEN'|'IN_REVIEW'|'RESOLVED'|'CLOSED';createdAt:string;user:{name:string;email:string;mobile?:string};order?:{orderNumber:string}|null};
class AdminSessionError extends Error{}
async function api<T>(path:string,init:RequestInit={},retry=true):Promise<T>{const res=await fetch(`${API}${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init.headers||{})}});const body=await res.json().catch(()=>({}));if((res.status===401||res.status===403)&&retry){const refresh=await fetch(`${API}/auth/admin/refresh`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}'});if(refresh.ok)return api<T>(path,init,false);throw new AdminSessionError('Your seller session expired. Sign in again.');}if(res.status===401||res.status===403)throw new AdminSessionError(body.message||'Seller administrator access required');if(!res.ok||!body.success)throw new Error(body.message||'Request failed');return body.data;}
export const AdminSupport:React.FC=()=>{const[tickets,setTickets]=useState<Ticket[]>([]);const[drafts,setDrafts]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[sessionExpired,setSessionExpired]=useState(false);const[replying,setReplying]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{setTickets(await api<Ticket[]>('/admin/customer-experience/support-tickets'));setSessionExpired(false);}catch(error){if(error instanceof AdminSessionError)setSessionExpired(true);else toastService.error('Support unavailable',error instanceof Error?error.message:'Unable to load support tickets.');}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();},[load]);
 const reply=async(ticket:Ticket)=>{const sellerReply=(drafts[ticket.id]||'').trim();if(!sellerReply){toastService.warning('Reply required','Write a response before sending.');return;}setReplying(ticket.id);try{await api(`/admin/customer-experience/support-tickets/${ticket.id}/reply`,{method:'PATCH',body:JSON.stringify({sellerReply,status:'RESOLVED'})});setDrafts(value=>({...value,[ticket.id]:''}));toastService.success('Reply sent','The customer received a website notification.');await load();}catch(error){if(error instanceof AdminSessionError)setSessionExpired(true);else toastService.error('Reply failed',error instanceof Error?error.message:'Please try again.');}finally{setReplying(null)}};
 if(sessionExpired)return <div className="max-w-xl mx-auto bg-white border border-amber-200 rounded-3xl p-8 text-center shadow-sm"><AlertCircle className="w-11 h-11 mx-auto text-amber-500"/><h2 className="text-xl font-extrabold text-[#032B42] mt-3">Seller session expired</h2><p className="text-sm text-slate-600 mt-2">Sign in again to securely view and reply to customer support tickets.</p><a href="/admin/login" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#0875B5] text-white px-5 py-3 font-bold"><LogIn className="w-4 h-4"/>Seller Sign In</a></div>;
 return <div className="space-y-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold text-[#032B42]">Customer Support</h1><p className="text-sm text-slate-500 mt-1">Read customer requests and respond without changing their original message.</p></div><button onClick={()=>void load()} disabled={loading} className="self-start sm:self-auto p-2.5 rounded-xl bg-sky-50 text-[#0875B5] disabled:opacity-50" aria-label="Refresh support tickets"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></div>{loading?<div className="bg-white rounded-3xl border border-sky-100 p-12 flex items-center justify-center gap-2 text-slate-500"><Loader2 className="w-5 h-5 animate-spin"/>Loading support requests…</div>:tickets.length===0?<div className="bg-white border border-dashed border-sky-200 rounded-3xl p-8 sm:p-12 text-center text-sm text-slate-500"><MessageSquare className="w-9 h-9 mx-auto text-sky-200 mb-3"/>No support tickets yet.</div>:<div className="grid grid-cols-1 gap-4">{tickets.map(ticket=><article key={ticket.id} className="bg-white rounded-3xl border border-sky-100 p-4 sm:p-6 shadow-sm space-y-4 overflow-hidden"><div className="flex flex-col sm:flex-row sm:items-start justify-between gap-2"><div className="min-w-0"><h2 className="font-extrabold text-[#032B42] break-words">{ticket.subject}</h2><p className="text-xs text-slate-500 mt-1 break-all">{ticket.user.name} • {ticket.user.email}{ticket.order?` • ${ticket.order.orderNumber}`:''}</p><p className="text-xs text-slate-400 mt-1">{new Date(ticket.createdAt).toLocaleString('en-IN')}</p></div><span className="self-start text-[11px] font-bold px-3 py-1.5 rounded-full bg-sky-50 text-[#0875B5] whitespace-nowrap">{ticket.status.replace('_',' ')}</span></div><div className="rounded-2xl bg-slate-50 border border-slate-100 p-4"><p className="text-sm text-slate-700 whitespace-pre-wrap break-words">{ticket.message}</p></div>{ticket.sellerReply&&<div className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4 text-sm"><strong className="text-emerald-800">Latest seller reply</strong><p className="mt-1 whitespace-pre-wrap break-words">{ticket.sellerReply}</p></div>}<div className="grid grid-cols-1 sm:grid-cols-[1fr_auto] gap-3"><textarea value={drafts[ticket.id]||''} onChange={e=>setDrafts(value=>({...value,[ticket.id]:e.target.value}))} rows={3} maxLength={5000} placeholder="Write a clear response to the customer…" className="w-full p-3.5 rounded-xl border border-sky-200 text-sm outline-none focus:border-[#0875B5] resize-y"/><button disabled={replying===ticket.id} onClick={()=>void reply(ticket)} className="premium-action-btn px-5 py-3 rounded-xl bg-[#0875B5] text-white font-bold text-sm flex items-center justify-center gap-2 disabled:opacity-60 sm:self-end">{replying===ticket.id?<Loader2 className="w-4 h-4 animate-spin"/>:<Send className="w-4 h-4"/>}Reply & Resolve</button></div></article>)}</div>}</div>;
};
