import React, { useEffect, useState } from 'react';
import { AlertTriangle, BarChart3, Download, MapPin, RefreshCw, ShoppingBag, TrendingUp, Users } from 'lucide-react';
import { AnalyticsData, analyticsService } from '../../services/analyticsService';
import { toastService } from '../../services/toastService';

const today = new Date().toISOString().slice(0, 10);
const prior = new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10);
const money = (value: number) => `₹${Math.round(value).toLocaleString('en-IN')}`;
const categoryLabel = (value: string) => ({ GUPPY: 'Guppies', FISH_FOOD: 'Fish Food', COMBO_PACK: 'Combo Packs', WHOLESALE: 'Wholesale' }[value] || value);

export const AdminAnalytics: React.FC = () => {
  const [from, setFrom] = useState(prior); const [to, setTo] = useState(today); const [data, setData] = useState<AnalyticsData | null>(null); const [loading, setLoading] = useState(true); const [lastUpdated,setLastUpdated]=useState<Date|null>(null);
  const load = async (quiet=false) => { if(!quiet)setLoading(true); try { setData(await analyticsService.overview(from, to));setLastUpdated(new Date()); } catch (error) { if(!quiet)toastService.error('Analytics unavailable', error instanceof Error ? error.message : 'Unable to load seller analytics.'); } finally { if(!quiet)setLoading(false); } };
  useEffect(() => { void load(); const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load(true)},30000);return()=>window.clearInterval(timer); }, [from,to]);
  const maximumTrend = Math.max(1, ...(data?.revenueTrend.map(row => row.revenue) || [1])); const maximumCategory = Math.max(1, ...(data?.categories.map(row => row.revenue) || [1]));
  if (loading && !data) return <div className="min-h-[45vh] flex items-center justify-center text-sm font-bold text-slate-500"><RefreshCw className="w-4 h-4 animate-spin mr-2"/>Loading database analytics…</div>;
  return <div className="space-y-7">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h1 className="text-2xl font-extrabold text-[#032B42]">Seller Analytics</h1><p className="text-xs text-slate-500 mt-1">Paid-order revenue, customer demand, inventory and delivery performance from PostgreSQL.</p><p className="text-xs text-emerald-600 font-bold mt-2">● Live updates every 30 seconds{lastUpdated?` • Updated ${lastUpdated.toLocaleTimeString('en-IN',{hour:'numeric',minute:'2-digit',second:'2-digit'})}`:''}</p></div><div className="flex flex-wrap items-end gap-2"><label className="text-[10px] font-bold text-slate-500">FROM<input type="date" value={from} max={to} onChange={event => setFrom(event.target.value)} className="block mt-1 p-2 rounded-xl border border-sky-200 text-xs"/></label><label className="text-[10px] font-bold text-slate-500">TO<input type="date" value={to} min={from} max={today} onChange={event => setTo(event.target.value)} className="block mt-1 p-2 rounded-xl border border-sky-200 text-xs"/></label><button disabled={loading} onClick={() => void load()} className="h-10 px-4 rounded-xl bg-[#0875B5] text-white text-xs font-bold flex items-center gap-1.5 disabled:opacity-60"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button><button onClick={() => void analyticsService.downloadCsv(from, to).catch(error => toastService.error('Export failed', error.message))} className="h-10 px-4 rounded-xl bg-emerald-600 text-white text-xs font-bold flex items-center gap-1.5"><Download className="w-4 h-4"/>CSV</button></div></div>
    {data && <>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[
        ['Revenue', money(data.metrics.revenue), TrendingUp, 'text-emerald-600 bg-emerald-50'], ['Paid Orders', data.metrics.paidOrders, ShoppingBag, 'text-[#0875B5] bg-sky-50'], ['Average Order', money(data.metrics.averageOrderValue), BarChart3, 'text-violet-600 bg-violet-50'], ['Customers', data.metrics.uniqueCustomers, Users, 'text-amber-600 bg-amber-50'],
      ].map(([label, value, Icon, color]) => <div key={String(label)} className="bg-white rounded-3xl border border-sky-100 p-5 shadow-sm"><div className="flex justify-between gap-2"><span className="text-[10px] uppercase font-bold text-slate-400">{label as string}</span><span className={`w-8 h-8 rounded-xl flex items-center justify-center ${color as string}`}><Icon className="w-4 h-4"/></span></div><p className="text-2xl font-extrabold text-[#032B42] mt-2">{value as React.ReactNode}</p></div>)}</div>
      <div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Revenue Trend</h2><div className="h-52 flex items-end gap-1 mt-5 overflow-x-auto">{data.revenueTrend.length ? data.revenueTrend.map(row => <div key={row.date} title={`${row.date}: ${money(row.revenue)}`} className="min-w-5 flex-1 max-w-12 flex flex-col justify-end items-center gap-1 h-full"><span className="text-[8px] text-slate-400">{row.orders}</span><div className="w-full rounded-t-lg bg-gradient-to-t from-[#0875B5] to-[#50D4EE]" style={{ height: `${Math.max(4, row.revenue / maximumTrend * 85)}%` }}/><span className="text-[8px] text-slate-400 rotate-[-45deg] origin-top-left whitespace-nowrap">{row.date.slice(5)}</span></div>) : <p className="text-xs text-slate-400 self-center mx-auto">No paid orders in this period.</p>}</div></div><div className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Order Performance</h2><div className="space-y-4 mt-5"><div><p className="text-xs text-slate-500">Received</p><p className="text-2xl font-extrabold text-emerald-600">{data.metrics.receivedOrders}</p></div><div><p className="text-xs text-slate-500">Fulfilment rate</p><p className="text-2xl font-extrabold text-[#0875B5]">{data.metrics.fulfillmentRate.toFixed(1)}%</p></div><div><p className="text-xs text-slate-500">Cancelled</p><p className="text-2xl font-extrabold text-rose-600">{data.metrics.cancelledOrders}</p></div></div></div></div>
      <div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Revenue by Product Line</h2><div className="space-y-4 mt-5">{data.categories.map(row => <div key={row.category}><div className="flex justify-between text-xs"><span className="font-bold">{categoryLabel(row.category)}</span><span>{money(row.revenue)} • {row.units} units</span></div><div className="h-2.5 bg-slate-100 rounded-full mt-1 overflow-hidden"><div className="h-full bg-[#0875B5] rounded-full" style={{ width: `${row.revenue / maximumCategory * 100}%` }}/></div></div>)}</div></section><section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Top Products</h2><div className="divide-y divide-sky-50 mt-3">{data.topProducts.slice(0, 6).map((row, index) => <div key={row.productId} className="py-3 flex justify-between gap-3 text-xs"><span className="font-bold text-slate-700">{index + 1}. {row.name}</span><span className="text-right"><strong>{money(row.revenue)}</strong><br/><span className="text-slate-400">{row.units} units</span></span></div>)}</div></section></div>
      <div className="grid lg:grid-cols-3 gap-5"><section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42] flex items-center gap-2"><MapPin className="w-4 h-4 text-[#0875B5]"/>Top Districts</h2>{data.districts.slice(0, 6).map(row => <div key={row.district} className="flex justify-between text-xs mt-4"><span className="font-bold">{row.district}</span><span>{row.orders} orders • {money(row.revenue)}</span></div>)}</section><section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42] flex items-center gap-2"><AlertTriangle className="w-4 h-4 text-amber-500"/>Stock Alerts</h2>{data.lowStock.length ? data.lowStock.slice(0, 8).map(row => <div key={row.id} className="flex justify-between text-xs mt-4"><span className="font-bold truncate pr-2">{row.name}</span><span className={row.stock === 0 ? 'text-rose-600 font-bold' : 'text-amber-600 font-bold'}>{row.stock} left</span></div>) : <p className="text-xs text-slate-400 mt-4">No low-stock products.</p>}</section><section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Availability Demand</h2>{data.availabilityDemand.length ? data.availabilityDemand.slice(0, 8).map(row => <div key={row.productId} className="flex justify-between text-xs mt-4"><span className="font-bold truncate pr-2">{row.name}</span><span className="text-violet-600 font-bold">{row.alerts} alerts</span></div>) : <p className="text-xs text-slate-400 mt-4">No active availability alerts.</p>}</section></div>
      <section className="bg-white rounded-3xl border border-sky-100 p-6"><h2 className="font-extrabold text-sm text-[#032B42]">Highest-Value Customers</h2><div className="overflow-x-auto mt-3"><table className="w-full text-xs"><thead><tr className="text-left text-slate-400 border-b border-sky-50"><th className="py-2">Customer</th><th>Email</th><th>Orders</th><th>Spend</th></tr></thead><tbody>{data.topCustomers.map(row => <tr key={row.userId} className="border-b border-sky-50"><td className="py-3 font-bold">{row.name}</td><td>{row.email}</td><td>{row.orders}</td><td className="font-bold">{money(row.spent)}</td></tr>)}</tbody></table></div></section>
    </>}
  </div>;
};
